sudo: required
services: 
    - docker

before_install:
    - docker build -t michaeliori/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true michaeliori/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-240065953873"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"


# k/BUse0/VEFS9HskoeMIIhr1TYkDWXEgl6EMVXi0